# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: vscode-settings
    # could also use /workspace/.vscode-remote/data/Machine/settings.json
    before: |
      mkdir -p ~/.config/Code/User/
      cat > /workspace/.vscode-remote/data/Machine/settings.json <<EOF
      {
        "extensions.ignoreRecommendations": true,
      }
      EOF


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
