# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: vscode-settings
    before: |
      mkdir -p ~/.config/Code/User/
      echo > ~/.config/Code/User/settings.json <<EOF
        {
          "extensions.ignoreRecommendations": "true",
        }
      EOF


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
