# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: vscode-settings
    # could also use ~/.config/Code/User/settings.json ?
    before: |
      SETTINGS_FILE_=/workspace/.vscode-remote/data/Machine/settings.json
      mkdir -p $(dirname ${SETTINGS_FILE_})
      cat > ${SETTINGS_FILE_} <<EOF
      {
        "extensions.ignoreRecommendations": true,
      }
      EOF


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
