name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nrf-connect: ["v1.6.1", "v1.7.1", "v1.8.0", "v1.9.1", "v2.0.0"]
    steps:
      # checkout v2, with recursive submodule update
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: check contains \#1
        if: contains(fromJson('["v1.8.0", "v1.9.1", "v2.0.0"]'), matrix.nrf-connect)
        run: |
          echo ${{ matrix.nrf-connect }}
          echo ${{ fromJson('["v1.8.0", "v1.9.1", "v2.0.0"]') }}

      - name: check contains
        if: contains(fromJson('["v1.6.1", "v1.7.1", "v1.8.0", "v1.9.1"]'), matrix.nrf-connect)
        run: |
          echo ${{ matrix.nrf-connect }}
